modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "AGPLv3"

[[mods]]
modId = "itig"
version = "${version}"
displayName = "I18n Translate In Game"
authors = "HO-Artisan"
description = '''
I18n Translate In Game
'''
#logoFile = ""

[[dependencies.itig]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itig]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itig]]
modId = "architectury"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.itig]]
modId = "cloth_config"
mandatory = true
versionRange = "[8,)"
ordering = "AFTER"
side = "BOTH"